version: '3.3'

services:

  db:
    container_name: postgres_ripio
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  django:
    container_name: django_ripio
    build:
      context: .
      dockerfile: Dockerfile-local
    command: ./startup_local.sh
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    depends_on:
      - db
    env_file: .env

volumes:
  postgres_data: